### ISSUE TITLE
0.0.6 asset release problems

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#1622]
Subtasks:
- [x] [Confirmed] Overall StanfordVL/ig_pipeline#1: windows are open in the initial state (even tho joint positions are 0)
- [x] Overall StanfordVL/ig_pipeline#2: For the following scenes, all objects have incorrect orientation (i.e. uniform orientation): Beechwood_1_int, Benevolence_0_int, Benevolence_1_int, Benevolence_2_int, Ihlen_1_int, Merom_0_int, Pomaria_0_int, Pomaria_1_int, Pomaria_2_int, Wainscott_1_int
- [x] [Confirmed] Overall StanfordVL/ig_pipeline#3: all pillows (sofa and bed) are instantiated as a bed or a sofa (i.e. a  few small sofas on top of a big sofa), same applies to pool_table (objects with floating joints)
- [x] Beechwood_0_int: door_ohagsq_0 is half open.
- [x] [Intended] Benevolence_0_int: [0, 0, 0] not inside the room
- [x] Benevolence_2_int: swivel_chair_mhsjfu_0 penetrating with breakfast_table_bmnubh_0 (maybe caused by wrong orientation: overall StanfordVL/ig_pipeline#2)
- [x] [Confirmed] Ihlen_0_int: sink_ksecxq_0 wrong orientation, a window hole doesn't have a window object 
- [x] Ihlen_0_int: door_lvgliq_0 half open
- [x] [Confirmed] Merom_1_int: picture_cltbty_0 should be a fixed-base object (this is a mistake from iG 2)
- [x] Pomaria_0_int: swivel_chair_lafeot_0 penetrating with breakfast_table_idnnmz_0  (maybe caused by wrong orientation: overall StanfordVL/ig_pipeline#2)
- [x] [Delayed for later] Pomaria_1_int: small gap between floors_abekig_0 and floors_zhumsu_0
- [x] [Confirmed] Wainscott_0_int: light link offsets (too dark)
