### ISSUE TITLE
Tracking (use subtasks): Scene changes for task matching

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#1742]
Subtasks:
- [ ] Beechwood_0_garden missing lawn object
- [ ] Add booth(s) to hall scenes (for selling-products-at-flea-market)
- [ ] Add desk to grocery store scenes (for picking-up-prescription)
- [ ] Add countertop to restaurant scenes (for clean_a_broiler_pan, cook_pork_ribs)
- [ ] Add space heater object to dataset (for de_ice_a_car)
- [ ] Add booth to corridor rooms in school scenes (for distributing_event_t_shirts, make-a-bake-sale-stand-stall)
- [ ] Add worktable, desk, and swivel_chair to garage rooms (for stripping_furniture, repairs_to_furniture, set_up_a_home_office_in_your_garage)
- [ ] split fridge into freezer + refrigerator (need freezer for make_popsicles)
- [ ] Add bookcase to private_office rooms in office scenes (for clean_up_your_desk, sorting_newspapers_for_recycling)
- [ ] Add coatrack to utility_rooms (for clean_a_quilt)
- [ ] Add shopping cart, shopping basket to all grocery stores (for buy-a-microwave-oven, picking-fruits-and-vegetables, taking-fish-out-of-freezer)
- [ ] Add sprinkler (at least two per scene) to gardens (for turning-sprinkler-on, turning-sprinkler-off)
- [ ] Add pedestal_table to entryway rooms (for hanging-address-numbers)
- [ ] Add more lawn_chairs (need min 4 for a single garden room) in gardens (for cleaning-patio-furniture)
