### ISSUE TITLE
Tracking issue for https://github.com/StanfordVL/iGibson3/pull/36

### ISSUE THREAD

**Issue by ChengshuLi** [StanfordVL/OmniGibson#38]
hard:
- [x] env_base: move `self._ignore_robot_object_collisions `, `self._ignore_robot_self_collisions`, `self._initial_pos_z_offset` to navigation tasks
- [x] env_base: resolve discrepancy between robot.action_space and robot.load_observation_space. Solution: add GymActionable, have env and controllable obj inherit from this
- [x] env_base: use filter_collisions in the util file
- [x] env_base: filter_collisions --> task, collision_step --> term condition, collision_caching (get collisions) --> simulator
- [x] env_base: move `robot.set_position(np.array([100.0, 100.0, 100.0]))` to the specific tasks that require moving the robots out of the scene and back in (e.g: point_nav_task)
- [x] robot_base: robot.action_space and robot.action_dim sometimes aren't the same
- [x] simulator: add more detailed comments to save/restore, dump/load state. 

features:
- [x] simulator: principled way of setting camera parameters
